version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.5
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2

    working_directory: ~/repo

    steps:
      # We are explictly not caching any of the dependencies / venv
      # pyenv + venv + caching don't seem to get along well.
      # See https://circleci.com/gh/yuvipanda/hubploy/154?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
      # for an example, causing a setuptools version mismatch
      - checkout

      - run:
          name: setup dependencies
          command: |
            sudo apt-get install tk-dev
            pyenv install 3.11.0
            pyenv global 3.11.0
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip setuptools
            pip install -r dev-requirements.txt
            pip install -e .
            git config --global user.email "ci@circleci"
            git config --global user.name "ci"

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            mkdir -p test-reports/unit
            py.test --cov=hubploy --junitxml=test-reports/unit/results.xml tests/ || true

      - run:
          name: upload coverage info to codecov
          command: |
            source venv/bin/activate
            codecov || true

      - store_test_results:
          path: test-reports

workflows:
  test-code:
    jobs:
    - build
  test-orb:
    jobs:
    - orb-tools/lint:
        lint-dir: orb/
