name: "python lint"
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: pip install ruff==0.6.9

      - name: Lint python files
        run: ruff check .
